// <auto-generated />
using DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Data.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20241023121819_InitialCreateMig")]
    partial class InitialCreateMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Bussines.Entities.Flight", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("JourneyId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<float>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("JourneyId");

                    b.ToTable("Flight", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "770202d7-08ba-49e8-ab66-8855be4007e9",
                            Destination = "BTA",
                            JourneyId = "9c9b5d14-e22b-4a4d-9792-f28e255e2a0d",
                            Origin = "BGA",
                            Price = 1000f
                        },
                        new
                        {
                            Id = "5d1391ea-faf9-4663-b74d-94e54843d52d",
                            Destination = "CTG",
                            JourneyId = "f0ebc49f-8e0a-4a3b-b3ed-7e14285be7a3",
                            Origin = "BTA",
                            Price = 2000f
                        },
                        new
                        {
                            Id = "e4efad61-b061-4fbf-aec8-4cd623536f95",
                            Destination = "MED",
                            JourneyId = "49f733c5-4b65-4390-bc60-ec7c3471e028",
                            Origin = "CAL",
                            Price = 1500f
                        },
                        new
                        {
                            Id = "0e8677a0-04ae-4fb3-9765-309a71c7624c",
                            Destination = "STA",
                            JourneyId = "b6ec5b59-2c9a-4df8-9072-1a9e23d9a1c5",
                            Origin = "MED",
                            Price = 4000f
                        },
                        new
                        {
                            Id = "a24a3289-30a5-4ec8-bd07-034051c76259",
                            Destination = "MED",
                            JourneyId = "d5a6a21c-023d-42ed-b98b-22d3a728f226",
                            Origin = "BGA",
                            Price = 1000f
                        },
                        new
                        {
                            Id = "097577c4-db87-4e10-a794-8382f2ed0484",
                            Destination = "CTG",
                            JourneyId = "9c9b5d14-e22b-4a4d-9792-f28e255e2a0d",
                            Origin = "MED",
                            Price = 1000f
                        },
                        new
                        {
                            Id = "b179ec78-f0cf-4bed-9139-7027300d72bf",
                            Destination = "CTG",
                            JourneyId = "f0ebc49f-8e0a-4a3b-b3ed-7e14285be7a3",
                            Origin = "CAL",
                            Price = 1000f
                        },
                        new
                        {
                            Id = "a73e31d5-7516-4374-968c-c69ccaf00ee9",
                            Destination = "MED",
                            JourneyId = "49f733c5-4b65-4390-bc60-ec7c3471e028",
                            Origin = "BTA",
                            Price = 1000f
                        });
                });

            modelBuilder.Entity("Bussines.Entities.Journey", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<float>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Journey", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "9c9b5d14-e22b-4a4d-9792-f28e255e2a0d",
                            Destination = "BTA",
                            Origin = "BGA",
                            Price = 1000f
                        },
                        new
                        {
                            Id = "f0ebc49f-8e0a-4a3b-b3ed-7e14285be7a3",
                            Destination = "CTG",
                            Origin = "BTA",
                            Price = 2000f
                        },
                        new
                        {
                            Id = "49f733c5-4b65-4390-bc60-ec7c3471e028",
                            Destination = "MED",
                            Origin = "CAL",
                            Price = 1500f
                        },
                        new
                        {
                            Id = "b6ec5b59-2c9a-4df8-9072-1a9e23d9a1c5",
                            Destination = "STA",
                            Origin = "MED",
                            Price = 4000f
                        },
                        new
                        {
                            Id = "d5a6a21c-023d-42ed-b98b-22d3a728f226",
                            Destination = "MED",
                            Origin = "BGA",
                            Price = 1000f
                        });
                });

            modelBuilder.Entity("Bussines.Entities.Transport", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FlightCarrier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FlightId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.ToTable("Transport", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "7d838ddc-1873-4697-92c9-79f13da906bd",
                            FlightCarrier = "AV",
                            FlightId = "770202d7-08ba-49e8-ab66-8855be4007e9",
                            FlightNumber = "8020"
                        },
                        new
                        {
                            Id = "0c5e7a1f-29c8-4340-832e-a1b277433f8c",
                            FlightCarrier = "AV",
                            FlightId = "5d1391ea-faf9-4663-b74d-94e54843d52d",
                            FlightNumber = "8030"
                        },
                        new
                        {
                            Id = "b02120b6-651d-4084-aa1c-47c86aed61c5",
                            FlightCarrier = "AV",
                            FlightId = "e4efad61-b061-4fbf-aec8-4cd623536f95",
                            FlightNumber = "8040"
                        },
                        new
                        {
                            Id = "e966a315-594e-41da-a00f-67c8fe48a906",
                            FlightCarrier = "AV",
                            FlightId = "0e8677a0-04ae-4fb3-9765-309a71c7624c",
                            FlightNumber = "8050"
                        },
                        new
                        {
                            Id = "46753d9b-2560-4b13-a51a-f6aa2ab8c732",
                            FlightCarrier = "AV",
                            FlightId = "a24a3289-30a5-4ec8-bd07-034051c76259",
                            FlightNumber = "8060"
                        },
                        new
                        {
                            Id = "41936778-333e-443f-b260-002577b8e467",
                            FlightCarrier = "AV",
                            FlightId = "770202d7-08ba-49e8-ab66-8855be4007e9",
                            FlightNumber = "8070"
                        },
                        new
                        {
                            Id = "a2d1de37-cfde-4b0b-989a-6c772d7452e2",
                            FlightCarrier = "AV",
                            FlightId = "5d1391ea-faf9-4663-b74d-94e54843d52d",
                            FlightNumber = "8080"
                        },
                        new
                        {
                            Id = "0b4a1620-3827-45fb-b621-dd3a8116550b",
                            FlightCarrier = "AV",
                            FlightId = "e4efad61-b061-4fbf-aec8-4cd623536f95",
                            FlightNumber = "8090"
                        });
                });

            modelBuilder.Entity("Bussines.Entities.Flight", b =>
                {
                    b.HasOne("Bussines.Entities.Journey", "Journey")
                        .WithMany("Flights")
                        .HasForeignKey("JourneyId");

                    b.Navigation("Journey");
                });

            modelBuilder.Entity("Bussines.Entities.Transport", b =>
                {
                    b.HasOne("Bussines.Entities.Flight", "Flight")
                        .WithMany("Transports")
                        .HasForeignKey("FlightId");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("Bussines.Entities.Flight", b =>
                {
                    b.Navigation("Transports");
                });

            modelBuilder.Entity("Bussines.Entities.Journey", b =>
                {
                    b.Navigation("Flights");
                });
#pragma warning restore 612, 618
        }
    }
}
